<a href="https://colab.research.google.com/github/shivaleelahvanaki-ops/Shivaleela/blob/main/Cryptarithmetic_Constraints.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Analyzing the mean of the covid data.csv

In [1]:
import numpy as np
import pandas as pd

In [5]:
covid_data = pd.read_csv("covid-data.csv")

In [6]:
covid_data.head(5)

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,24/02/2020,5,5,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,25/02/2020,5,0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,26/02/2020,5,0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,27/02/2020,5,0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,28/02/2020,5,0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN

In [7]:
covid_data = covid_data[['iso_code','continent','location','date','total_cases','new_cases']]

In [8]:
covid_data.head(5)

  iso_code continent     location        date  total_cases  new_cases
0      AFG      Asia  Afghanistan  24/02/2020            5          5
1      AFG      Asia  Afghanistan  25/02/2020            5          0
2      AFG      Asia  Afghanistan  26/02/2020            5          0
3      AFG      Asia  Afghanistan  27/02/2020            5          0
4      AFG      Asia  Afghanistan  28/02/2020            5          0

In [9]:
covid_data.dtypes

iso_code       object
continent      object
location       object
date           object
total_cases     int64
new_cases       int64
dtype: object

In [11]:
covid_data.shape

(5818, 6)

In [12]:
data_mean = np.mean(covid_data["new_cases"])
data_mean

np.float64(8814.365761430045)

In [13]:
data_mean = covid_data["new_cases"].mean()
data_mean

np.float64(8814.365761430045)

In [14]:
data_median = np.median(covid_data["new_cases"])
data_median

np.float64(261.0)

In [15]:
data_median = covid_data["new_cases"].median()
data_median

261.0

In [16]:
from scipy import stats

In [17]:
data_mode = covid_data["new_cases"].mode()
data_mode

0    0
Name: new_cases, dtype: int64

In [18]:
data_mode = covid_data["new_cases"].mode()
data_mode

0    0
Name: new_cases, dtype: int64

In [19]:
data_variance = np.var(covid_data["new_cases"])
data_variance

451321915.92810047

In [20]:
covid_data["new_cases"].var()

451399502.6422019

In [21]:
data_sd = np.std(covid_data["new_cases"])
data_sd

21244.33844411495

In [22]:
covid_data["new_cases"].std()

21246.16442189512

In [23]:
data_max = np.max(covid_data["new_cases"])
data_min = np.min(covid_data["new_cases"])

In [24]:
print(data_max,data_min)

287149 0

In [25]:
data_range = data_max - data_min
data_range

287149

In [26]:
data_max = covid_data["new_cases"].max()
data_min = covid_data["new_cases"].min()

In [27]:
data_range = data_max - data_min
data_range

287149

In [28]:
data_percentile = np.percentile(covid_data["new_cases"],60)
data_percentile

np.float64(591.3999999999996)

In [29]:
data_quartile = np.quantile(covid_data["new_cases"],0.75)
data_quartile

np.float64(3666.0)

In [30]:
data_quartile = np.quantile(covid_data["new_cases"],0.75)
data_quartile

np.float64(3666.0)

In [31]:
data_IQR = stats.iqr(covid_data["new_cases"])
data_IQR

np.float64(3642.0)